export const CURRENCIES = [
    // Popular
    { code: 'USD', flag: '🇺🇸', name: 'US Dollar', country: 'United States', symbol: '$' },
    { code: 'EUR', flag: '🇪🇺', name: 'Euro', country: 'Eurozone', symbol: '€' },
    { code: 'GBP', flag: '🇬🇧', name: 'British Pound', country: 'United Kingdom', symbol: '£' },
    { code: 'JPY', flag: '🇯🇵', name: 'Japanese Yen', country: 'Japan', symbol: '¥' },
    { code: 'AUD', flag: '🇦🇺', name: 'Australian Dollar', country: 'Australia', symbol: 'A$' },
    { code: 'CAD', flag: '🇨🇦', name: 'Canadian Dollar', country: 'Canada', symbol: 'C$' },
    { code: 'CHF', flag: '🇨🇭', name: 'Swiss Franc', country: 'Switzerland', symbol: 'CHF' },
    { code: 'CNY', flag: '🇨🇳', name: 'Chinese Yuan', country: 'China', symbol: '¥' },
    { code: 'INR', flag: '🇮🇳', name: 'Indian Rupee', country: 'India', symbol: '₹' },
    { code: 'SGD', flag: '🇸🇬', name: 'Singapore Dollar', country: 'Singapore', symbol: 'S$' },
    { code: 'AED', flag: '🇦🇪', name: 'UAE Dirham', country: 'United Arab Emirates', symbol: 'د.إ' },
    { code: 'SAR', flag: '🇸🇦', name: 'Saudi Riyal', country: 'Saudi Arabia', symbol: 'ر.س' },
    { code: 'KWD', flag: '🇰🇼', name: 'Kuwaiti Dinar', country: 'Kuwait', symbol: 'د.ك' },
    { code: 'QAR', flag: '🇶🇦', name: 'Qatari Riyal', country: 'Qatar', symbol: 'ر.ق' },
    { code: 'BHD', flag: '🇧🇭', name: 'Bahraini Dinar', country: 'Bahrain', symbol: '.د.ب' },
    { code: 'OMR', flag: '🇴🇲', name: 'Omani Rial', country: 'Oman', symbol: 'ر.ع.' },
    { code: 'JOD', flag: '🇯🇴', name: 'Jordanian Dinar', country: 'Jordan', symbol: 'د.ا' },
    { code: 'EGP', flag: '🇪🇬', name: 'Egyptian Pound', country: 'Egypt', symbol: 'E£' },
    { code: 'PKR', flag: '🇵🇰', name: 'Pakistani Rupee', country: 'Pakistan', symbol: '₨' },
    { code: 'BDT', flag: '🇧🇩', name: 'Bangladeshi Taka', country: 'Bangladesh', symbol: '৳' },
    { code: 'LKR', flag: '🇱🇰', name: 'Sri Lankan Rupee', country: 'Sri Lanka', symbol: 'Rs' },
    { code: 'NPR', flag: '🇳🇵', name: 'Nepalese Rupee', country: 'Nepal', symbol: 'Rs' },
    { code: 'THB', flag: '🇹🇭', name: 'Thai Baht', country: 'Thailand', symbol: '฿' },
    { code: 'MYR', flag: '🇲🇾', name: 'Malaysian Ringgit', country: 'Malaysia', symbol: 'RM' },
    { code: 'IDR', flag: '🇮🇩', name: 'Indonesian Rupiah', country: 'Indonesia', symbol: 'Rp' },
    { code: 'PHP', flag: '🇵🇭', name: 'Philippine Peso', country: 'Philippines', symbol: '₱' },
    { code: 'VND', flag: '🇻🇳', name: 'Vietnamese Dong', country: 'Vietnam', symbol: '₫' },
    { code: 'KRW', flag: '🇰🇷', name: 'South Korean Won', country: 'South Korea', symbol: '₩' },
    { code: 'HKD', flag: '🇭🇰', name: 'Hong Kong Dollar', country: 'Hong Kong', symbol: 'HK$' },
    { code: 'TWD', flag: '🇹🇼', name: 'Taiwan Dollar', country: 'Taiwan', symbol: 'NT$' },
    { code: 'NZD', flag: '🇳🇿', name: 'New Zealand Dollar', country: 'New Zealand', symbol: 'NZ$' },
    { code: 'ZAR', flag: '🇿🇦', name: 'South African Rand', country: 'South Africa', symbol: 'R' },
    { code: 'NGN', flag: '🇳🇬', name: 'Nigerian Naira', country: 'Nigeria', symbol: '₦' },
    { code: 'KES', flag: '🇰🇪', name: 'Kenyan Shilling', country: 'Kenya', symbol: 'KSh' },
    { code: 'GHS', flag: '🇬🇭', name: 'Ghanaian Cedi', country: 'Ghana', symbol: 'GH₵' },
    { code: 'MAD', flag: '🇲🇦', name: 'Moroccan Dirham', country: 'Morocco', symbol: 'MAD' },
    { code: 'TND', flag: '🇹🇳', name: 'Tunisian Dinar', country: 'Tunisia', symbol: 'DT' },
    { code: 'DZD', flag: '🇩🇿', name: 'Algerian Dinar', country: 'Algeria', symbol: 'DA' },
    { code: 'TRY', flag: '🇹🇷', name: 'Turkish Lira', country: 'Turkey', symbol: '₺' },
    { code: 'RUB', flag: '🇷🇺', name: 'Russian Ruble', country: 'Russia', symbol: '₽' },
    { code: 'UAH', flag: '🇺🇦', name: 'Ukrainian Hryvnia', country: 'Ukraine', symbol: '₴' },
    { code: 'PLN', flag: '🇵🇱', name: 'Polish Zloty', country: 'Poland', symbol: 'zł' },
    { code: 'SEK', flag: '🇸🇪', name: 'Swedish Krona', country: 'Sweden', symbol: 'kr' },
    { code: 'NOK', flag: '🇳🇴', name: 'Norwegian Krone', country: 'Norway', symbol: 'kr' },
    { code: 'DKK', flag: '🇩🇰', name: 'Danish Krone', country: 'Denmark', symbol: 'kr' },
    { code: 'CZK', flag: '🇨🇿', name: 'Czech Koruna', country: 'Czech Republic', symbol: 'Kč' },
    { code: 'HUF', flag: '🇭🇺', name: 'Hungarian Forint', country: 'Hungary', symbol: 'Ft' },
    { code: 'RON', flag: '🇷🇴', name: 'Romanian Leu', country: 'Romania', symbol: 'lei' },
    { code: 'BGN', flag: '🇧🇬', name: 'Bulgarian Lev', country: 'Bulgaria', symbol: 'лв' },
    { code: 'HRK', flag: '🇭🇷', name: 'Croatian Kuna', country: 'Croatia', symbol: 'kn' },
    { code: 'RSD', flag: '🇷🇸', name: 'Serbian Dinar', country: 'Serbia', symbol: 'дин.' },
    { code: 'MXN', flag: '🇲🇽', name: 'Mexican Peso', country: 'Mexico', symbol: '$' },
    { code: 'BRL', flag: '🇧🇷', name: 'Brazilian Real', country: 'Brazil', symbol: 'R$' },
    { code: 'ARS', flag: '🇦🇷', name: 'Argentine Peso', country: 'Argentina', symbol: '$' },
    { code: 'CLP', flag: '🇨🇱', name: 'Chilean Peso', country: 'Chile', symbol: '$' },
    { code: 'COP', flag: '🇨🇴', name: 'Colombian Peso', country: 'Colombia', symbol: '$' },
    { code: 'PEN', flag: '🇵🇪', name: 'Peruvian Sol', country: 'Peru', symbol: 'S/.' },
    { code: 'VES', flag: '🇻🇪', name: 'Venezuelan Bolivar', country: 'Venezuela', symbol: 'Bs.' },
    { code: 'UYU', flag: '🇺🇾', name: 'Uruguayan Peso', country: 'Uruguay', symbol: '$U' },
    { code: 'BOB', flag: '🇧🇴', name: 'Bolivian Boliviano', country: 'Bolivia', symbol: 'Bs.' },
    { code: 'PYG', flag: '🇵🇾', name: 'Paraguayan Guarani', country: 'Paraguay', symbol: '₲' },
    { code: 'ILS', flag: '🇮🇱', name: 'Israeli Shekel', country: 'Israel', symbol: '₪' },
    { code: 'KZT', flag: '🇰🇿', name: 'Kazakhstani Tenge', country: 'Kazakhstan', symbol: '₸' },
    { code: 'UZS', flag: '🇺🇿', name: 'Uzbekistani Sum', country: 'Uzbekistan', symbol: 'so\'m' },
    { code: 'GEL', flag: '🇬🇪', name: 'Georgian Lari', country: 'Georgia', symbol: '₾' },
    { code: 'AMD', flag: '🇦🇲', name: 'Armenian Dram', country: 'Armenia', symbol: '֏' },
    { code: 'AZN', flag: '🇦🇿', name: 'Azerbaijani Manat', country: 'Azerbaijan', symbol: '₼' },
    { code: 'IRR', flag: '🇮🇷', name: 'Iranian Rial', country: 'Iran', symbol: '﷼' },
    { code: 'IQD', flag: '🇮🇶', name: 'Iraqi Dinar', country: 'Iraq', symbol: 'ع.د' },
    { code: 'LBP', flag: '🇱🇧', name: 'Lebanese Pound', country: 'Lebanon', symbol: 'ل.ل' },
    { code: 'SYP', flag: '🇸🇾', name: 'Syrian Pound', country: 'Syria', symbol: '£' },
    { code: 'YER', flag: '🇾🇪', name: 'Yemeni Rial', country: 'Yemen', symbol: '﷼' },
    { code: 'AFN', flag: '🇦🇫', name: 'Afghan Afghani', country: 'Afghanistan', symbol: '؋' },
    { code: 'MMK', flag: '🇲🇲', name: 'Myanmar Kyat', country: 'Myanmar', symbol: 'K' },
    { code: 'KHR', flag: '🇰🇭', name: 'Cambodian Riel', country: 'Cambodia', symbol: '៛' },
    { code: 'LAK', flag: '🇱🇦', name: 'Lao Kip', country: 'Laos', symbol: '₭' },
    { code: 'MNT', flag: '🇲🇳', name: 'Mongolian Tugrik', country: 'Mongolia', symbol: '₮' },
    { code: 'ETB', flag: '🇪🇹', name: 'Ethiopian Birr', country: 'Ethiopia', symbol: 'Br' },
    { code: 'TZS', flag: '🇹🇿', name: 'Tanzanian Shilling', country: 'Tanzania', symbol: 'TSh' },
    { code: 'UGX', flag: '🇺🇬', name: 'Ugandan Shilling', country: 'Uganda', symbol: 'USh' },
    { code: 'RWF', flag: '🇷🇼', name: 'Rwandan Franc', country: 'Rwanda', symbol: 'RF' },
    { code: 'XOF', flag: '🌍', name: 'West African CFA Franc', country: 'West Africa', symbol: 'CFA' },
    { code: 'XAF', flag: '🌍', name: 'Central African CFA Franc', country: 'Central Africa', symbol: 'CFA' },
    { code: 'MZN', flag: '🇲🇿', name: 'Mozambican Metical', country: 'Mozambique', symbol: 'MT' },
    { code: 'ZMW', flag: '🇿🇲', name: 'Zambian Kwacha', country: 'Zambia', symbol: 'ZK' },
    { code: 'BWP', flag: '🇧🇼', name: 'Botswana Pula', country: 'Botswana', symbol: 'P' },
    { code: 'NAD', flag: '🇳🇦', name: 'Namibian Dollar', country: 'Namibia', symbol: '$' },
    { code: 'MUR', flag: '🇲🇺', name: 'Mauritian Rupee', country: 'Mauritius', symbol: '₨' },
    { code: 'SCR', flag: '🇸🇨', name: 'Seychellois Rupee', country: 'Seychelles', symbol: '₨' },
    { code: 'CRC', flag: '🇨🇷', name: 'Costa Rican Colon', country: 'Costa Rica', symbol: '₡' },
    { code: 'GTQ', flag: '🇬🇹', name: 'Guatemalan Quetzal', country: 'Guatemala', symbol: 'Q' },
    { code: 'HNL', flag: '🇭🇳', name: 'Honduran Lempira', country: 'Honduras', symbol: 'L' },
    { code: 'NIO', flag: '🇳🇮', name: 'Nicaraguan Cordoba', country: 'Nicaragua', symbol: 'C$' },
    { code: 'PAB', flag: '🇵🇦', name: 'Panamanian Balboa', country: 'Panama', symbol: 'B/.' },
    { code: 'DOP', flag: '🇩🇴', name: 'Dominican Peso', country: 'Dominican Republic', symbol: 'RD$' },
    { code: 'JMD', flag: '🇯🇲', name: 'Jamaican Dollar', country: 'Jamaica', symbol: 'J$' },
    { code: 'TTD', flag: '🇹🇹', name: 'Trinidad & Tobago Dollar', country: 'Trinidad & Tobago', symbol: 'TT$' },
    { code: 'BBD', flag: '🇧🇧', name: 'Barbadian Dollar', country: 'Barbados', symbol: '$' },
    { code: 'FJD', flag: '🇫🇯', name: 'Fijian Dollar', country: 'Fiji', symbol: '$' },
    { code: 'PGK', flag: '🇵🇬', name: 'Papua New Guinean Kina', country: 'Papua New Guinea', symbol: 'K' },
    { code: 'WST', flag: '🇼🇸', name: 'Samoan Tala', country: 'Samoa', symbol: 'T' },
];

export const POPULAR_CODES = ['USD', 'EUR', 'GBP', 'INR', 'AED', 'SAR', 'KWD', 'JPY', 'AUD', 'SGD', 'CAD', 'THB'];
